sudo: required
language: c
before_script: "cd _mirage && bash -ex ./travis.sh"
script: "bash -ex ./build && ls -al static-www.*"
env:
  matrix:
  - MIRAGE_BACKEND=xen DEPLOY=0
  - MIRAGE_BACKEND=unix
