sudo: required
language: c
before_script: bash -ex _mirage/travis.sh
script: COMPRESS_IMAGE=1 bash -ex ./build
env:
  matrix:
  - MIRAGE_BACKEND=xen DEPLOY=0
  - MIRAGE_BACKEND=unix
deploy:
  provider: releases
  api_key:
    secure: AZfg1KsMdcDgClGbPrIrTJAGVwPTdqPlRpauzaPTJ3yE7uqbXHCdyOqbrgNswiZisMgPe4+LRZro+4SyOY5HjqG8LRtSAw9M5XjvqvcXhUffdnglzz7U9chEg4vVeNbOeIf+8AKA8kblo/45BByTPKziahGGv9YpTRHo8HBb7B8ScolAT3R7gqEMVFo5af+eVk86s1QyF8dr3u6hq5JPxLXKMXVz9Qp/ocQ5lpYYIAUENkm271UQGZkxEqrhMKjuhH5YDpmMxwF3vf7Ntog5l+abZ+wNrKycUzMD7OVx/DZ4I5zODnVMaVP+b3Cld7DQOXMmR0ZGqBjvlHCz4eMeQi/XEA3l7gskOlo7lWln4nultdfzibbPYMv9FdzMmDhiZJ6Mr9ILWrxqTGMc0QpxM7WABDZQ7vFxFN1TFM88fcZVNiZVOmy1mDSvxXJP2XMKzbfUBOEPPuUsu0PbStLMhzCboZtodaN/H5xtSNQl0PSazmKkw+g+O2QklUvOS1j4W3rpd45ZDvVgGW9K3j6hV/BA23ap2q//jllqAywPsR9didVSp2lElntuLW84w3LAfcnjN7ZTK4TL8XB0U7z120KKmg8odTPkU80WLErIz6JPbetNN8+q/HVM4tjWlKEmiGOIiAUlNseI9JyIJRXnBvtshLvEGqXUzxbqSEq+fns=
  file: static-www.xen.bz2
  on:
    tags: true
