#!/bin/bash
set -e -E -u

: ${COMPRESS_IMAGE:=} ${NET:=DIRECT} ${DHCP:=true}

NAME=$(basename $PWD)
XEN_IMAGE=$NAME.xen
TOP_DIR=$PWD
BUILD_DIR=$PWD/_build


eval $(opam config env)

rm -f *.bz2
mkdir -p $BUILD_DIR
cp config.ml dispatch.ml $BUILD_DIR

cd $BUILD_DIR
NET=$NET DHCP=$DHCP mirage configure --xen
rm -f *.xen*
make
cd $TOP_DIR

cp $BUILD_DIR/*.xen $XEN_IMAGE
if [[ -n $COMPRESS_IMAGE ]]; then
    echo "compressing image"
    bzip2 $XEN_IMAGE
fi

ls -al $NAME.*

echo "done"
